services:
  - type: web
    name: Web-Application---Predicting-Airline-Passenger-Satisfaction-Using-Machine-Learning-Model
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
