services:
  - type: web
    name: Web-Application---Predicting-Airline-Passenger-Satisfaction-Using-Machine-Learning-Model
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
